CREATE DATABASE bike_tools

USE DATABASE bike_tools

CREATE TABLE users(
    id INT(11)NOT NULL,
    username VARCHAR(16)NOT NULL,
    password VARCHAR(60)NOT NULL,
    fullname VARCHAR(100)NOT NULL
)

ALTER TABLE users
ADD PRIMARY KEY (id);

ALTER TABLE users

MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT =2;


CREATE TABLE workshop(
    id INT(11)NOT NULL,
    tittle VARCHAR(150)NOT NULL,
    address VARCHAR(150)NOT NULL,
    description TEXT,
    user_id INT(11),
    create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAIN fk_user FOREIGN KEY (user_id) REFERENCES users(id)
);

AFTER TABLE workshop
ADD PRIMARY KEY (id);

ALTER TABLE workshop
MODIFY id INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT =2;

ALTER TABLE workshop
MODIFY phone VARCHAR(10) NOT NULL;

ALTER TABLE workshop
ADD schedule VARCHAR(100)NOT NULL;

ALTER TABLE workshop
ADD url VARCHAR(250)NOT NULL